### ISSUE TITLE
Stuck at vectorize data...

### ISSUE THREAD

**Issue by sanchit123k** [MahmoudWahdan/dialog-nlu#7]
.The code is stucked at 

read data ...
vectorize data ...

Any solution?

**Comment by MahmoudWahdan** [comment]
Please, provide more details like what is your operating system? which script are you running? with which command? Was it running before?

**Comment by MahmoudWahdan** [comment]
@sanchit123k FYI the pre-trained model is downloaded downloaded first from tensorflow hub. This takes time for the first time, after that it loads it from a caching directory in your system. 
The stuck behavior may be slowness in your internet or may be because of uncomplete/damaged version of the pre-trained model in the cached model in your system.
After that the training data is used to fine tune the pre-trained model, resulting in the joint NLU model.
I hope this will help you. Please, let me know.
